# -*- coding: utf-8 -*-
"""COCO_Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tgun5yxPHO1AbaW_bvUZ3pv0qEGMJ7RQ
"""

import json
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image

# For using COCO API
!pip install pycocotools
from pycocotools.coco import COCO

# Downloading dataset
# Ran out of disk space if I tried to add any other files
!wget http://images.cocodataset.org/zips/train2017.zip

!unzip train2017.zip

coco = COCO("train2017")

# Get list of category_ids
# Used bicycles in this to test
category_ids = coco.getCatIds(['bicycle'])

# Get list of image_ids which contain bicycles
image_ids = coco.getImgIds(catIds=[2])
print(image_ids[0:5])

# Getting annotation ids of random image from bicycle data
annotation_ids = coco.getAnnIds(imgIds=196610, catIds=[2])
print(len(annotation_ids))

anns = coco.loadAnns(annotation_ids)

# Getting annotation coords
for ann in anns:
    print(ann['bbox'])

image_id = 196610
 
images_path = "train2017"
image_name = str(image_id).zfill(12)+".jpg"
image = Image.open(images_path+image_name) # Had issue here opening images by path+name
 
fig, ax = plt.subplots()
 
# Draw boxes and add label to each box
for ann in anns:
    box = ann['bbox']
    bb = patches.Rectangle((box[0],box[1]), box[2],box[3], linewidth=2, edgecolor="blue", facecolor="none")
    ax.add_patch(bb)
 
ax.imshow(image)
plt.show()